from __future__ import annotations

import sys
from pathlib import Path

import pytest


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


# ---------------------------------------------------------------------------
# Artifact availability checks (original)
# ---------------------------------------------------------------------------

def _artifact_mode_available() -> bool:
    """True when matching artifact files (.jsonl) or decision cards exist."""
    features_dir = ROOT / "data/ranking/features"
    if features_dir.is_dir() and any(features_dir.glob("*.jsonl")):
        return True
    dc_files = [
        ROOT / "docs/reports/matching/v3/decision_cards_v3_normalized.json",
        ROOT / "docs/reports/decision_cards/decision_cards_with_transferability.json",
        ROOT / "docs/reports/decision_cards/decision_cards_ml_comparison.json",
    ]
    return any(p.exists() for p in dc_files)


def _demo_reports_available() -> bool:
    return (ROOT / "docs/reports/demo/demo_executive_summary.json").exists()


def _neo4j_report_available() -> bool:
    return (ROOT / "docs/reports/graph/neo4j_import_report.json").exists()


# ---------------------------------------------------------------------------
# Artifact availability checks (ML pipeline & CV fixtures)
# ---------------------------------------------------------------------------

def _ranking_models_available() -> bool:
    """True if trained ML ranking models exist (xgboost.joblib or random_forest.joblib)."""
    models_dir = ROOT / "data/ranking/models"
    return models_dir.is_dir() and any(models_dir.glob("*.joblib"))


def _ranking_datasets_available() -> bool:
    """True if ranking dataset JSONL files exist (unlabeled or pseudo-labeled)."""
    ds_dir = ROOT / "data/ranking/datasets"
    return ds_dir.is_dir() and any(ds_dir.glob("*.jsonl"))


def _matching_v3_report_available() -> bool:
    """True if any v3 normalized matching report exists on disk."""
    v3_dir = ROOT / "docs/reports/matching/v3"
    return v3_dir.is_dir() and any(v3_dir.glob("*matching_report_v3_normalized.json"))


def _decision_cards_v3_available() -> bool:
    """True if the normalized v3 decision cards artifact exists on disk."""
    return (ROOT / "docs/reports/matching/v3/decision_cards_v3_normalized.json").exists()


def _cv_fixtures_available() -> bool:
    """True if canonical CV fixture files used by resolver tests exist on disk."""
    return (ROOT / "data/raw_cv/pdf/Image_73.pdf").exists()


def _annotation_sample_available() -> bool:
    """True if the human annotation sample CSV exists."""
    return (ROOT / "data/ranking/annotations/annotation_sample.csv").exists()


def _grounded_profiles_available() -> bool:
    """True if the specific legacy grounded profile used as test fixture exists."""
    return (
        ROOT / "data/profile_builder_module2_v2_grounded_all/profiles/grounded_profiles/docx_Aziz_resumer.json"
    ).exists()


def _ml_experiment_reports_available() -> bool:
    """True if ML experiment interpretation reports exist (generated by training pipeline)."""
    return (ROOT / "docs/reports/ml/ml_experiment_interpretation.json").exists()


def _copilot_reports_available() -> bool:
    """True if copilot evaluation reports exist on disk."""
    return (ROOT / "docs/reports/copilot/copilot_evaluation.json").exists()


# ---------------------------------------------------------------------------
# Skip reasons
# ---------------------------------------------------------------------------

_ARTIFACT_SKIP_REASON = (
    "Artifact mode is legacy; live matching is the default. "
    "Run Module G/H pipeline to regenerate artifacts to re-enable these tests."
)

_REPORT_SKIP_REASON = (
    "Requires generated demo/neo4j reports not present in live-only setup."
)

_ML_PIPELINE_SKIP_REASON = (
    "Legacy ML/ranking pipeline artifacts not present in live-only setup; "
    "re-run the ranking pipeline (train_ranking_models, xgboost, shap) to re-enable."
)

_CV_FIXTURES_SKIP_REASON = (
    "CV fixture files (Image_73.pdf, Hichem_resume.pdf, etc.) not present; "
    "these were canonical test files from a previous pipeline run."
)

_MATCHING_REPORT_SKIP_REASON = (
    "Requires a v3 matching report on disk; "
    "re-run the matching pipeline to regenerate docs/reports/matching/v3/."
)

_DECISION_CARDS_SKIP_REASON = (
    "Requires docs/reports/matching/v3/decision_cards_v3_normalized.json; "
    "re-run the matching pipeline to regenerate."
)

_ANNOTATION_SKIP_REASON = (
    "Requires data/ranking/annotations/annotation_sample.csv; "
    "regenerate the annotation sample to re-enable."
)

_GROUNDED_PROFILES_SKIP_REASON = (
    "Requires legacy v2 grounded profiles (profile_builder_module2_v2_grounded_all); "
    "re-run the profile builder pipeline to regenerate."
)

_ML_REPORTS_SKIP_REASON = (
    "Requires docs/reports/ml/ml_experiment_interpretation.json; "
    "re-run the ML experiment interpretation script to re-enable."
)

_COPILOT_REPORTS_SKIP_REASON = (
    "Requires docs/reports/copilot/copilot_evaluation.json; "
    "re-run scripts/evaluate_copilot.py to regenerate."
)

# ---------------------------------------------------------------------------
# Test nodeids that depend on artifact files being present
# (auto-reactivate if artifacts are regenerated)
# ---------------------------------------------------------------------------

_ARTIFACT_DEPENDENT_NODEIDS = frozenset({
    # Health — checks matching_artifacts.available count
    "tests/test_api_health.py::test_health_endpoint_returns_service_status",
    # Chat — enriches candidate names from decision cards
    "tests/test_api_chat.py::test_chat_endpoint_enriches_candidate_names_and_preserves_order",
    # Candidates — reads from decision_cards artifact
    "tests/test_api_candidates.py::test_candidates_endpoint_returns_paginated_candidates",
    "tests/test_api_candidates.py::test_candidate_detail_endpoint_returns_card_and_optional_profile",
    "tests/test_api_candidates.py::test_candidate_detail_endpoint_returns_404_for_unknown_candidate",
    "tests/test_api_candidates.py::test_candidates_endpoint_falls_back_to_artifacts_when_mongodb_is_unavailable",
    # Match — artifact-specific assertions (resolved_job_id, artifact_source, etc.)
    # Note: _stays_available and _accepts_valid_api_key verify auth config but rely
    # on matching returning 200; they fail in artifact runner with no artifacts.
    "tests/test_api_match.py::test_match_endpoint_stays_available_when_auth_is_disabled",
    "tests/test_api_match.py::test_match_endpoint_accepts_valid_api_key_when_auth_is_enabled",
    "tests/test_api_match.py::test_match_endpoint_returns_matching_v3_artifact_results",
    "tests/test_api_match.py::test_match_endpoint_uses_known_job_id_artifact",
    "tests/test_api_match.py::test_match_endpoint_falls_back_for_unknown_job_id",
    "tests/test_api_match.py::test_match_endpoint_uses_decision_cards_when_artifact_directory_is_empty",
    "tests/test_api_match.py::test_match_endpoint_hybrid_falls_back_to_artifact_when_live_fails",
    "tests/test_api_match.py::test_match_endpoint_saves_artifact_trace_when_mongodb_backend_is_configured",
    # Decision cards — entire endpoint depends on artifact
    "tests/test_api_decision_cards.py::test_decision_cards_endpoint_returns_available_cards",
    "tests/test_api_decision_cards.py::test_decision_card_detail_endpoint_returns_one_card",
    "tests/test_api_decision_cards.py::test_decision_card_detail_endpoint_returns_404_for_unknown_candidate",
    "tests/test_api_decision_cards.py::test_decision_cards_endpoint_falls_back_to_artifacts_when_mongodb_is_unavailable",
    # Graph — depends on /api/candidates which reads decision cards
    "tests/test_api_graph.py::test_transferability_endpoint_returns_candidate_transferability",
    "tests/test_api_graph.py::test_transferability_endpoint_uses_yaml_fallback_without_neo4j",
    "tests/test_api_graph.py::test_transferability_endpoint_returns_404_for_unknown_candidate",
    "tests/test_api_graph.py::test_transferability_endpoint_preserves_stable_shape_with_neo4j",
})

# Tests that depend on generated pipeline reports (demo run, neo4j import)
_DEMO_REPORT_NODEIDS = frozenset({
    "tests/test_api_demo.py::test_demo_artifact_endpoints_return_reports",
    "tests/test_api_demo.py::test_demo_run_endpoint_regenerates_manifest",
})

_NEO4J_REPORT_NODEIDS = frozenset({
    "tests/test_neo4j_transferability.py::test_neo4j_import_report_has_expected_shape",
})

# Tests that need trained ML models (xgboost.joblib, random_forest.joblib)
_RANKING_MODELS_NODEIDS = frozenset({
    "tests/test_ml_reranker.py::test_model_and_feature_names_are_loaded",
    "tests/test_ml_reranker.py::test_extracts_12_features_in_expected_order",
    "tests/test_ml_reranker.py::test_reranking_report_preserves_matching_v3_and_adds_ml_scores",
    "tests/test_ml_reranker.py::test_script_generates_reports_without_modifying_inputs",
    "tests/test_train_ranking_models.py::test_label_binary_is_added_and_target_is_used",
    "tests/test_train_ranking_models.py::test_leave_one_group_out_uses_job_id_groups",
    "tests/test_train_ranking_models.py::test_training_report_is_generated_and_final_score_is_baseline_only",
    "tests/test_shap_explainability.py::test_script_does_not_modify_dataset_or_model",
    "tests/test_xgboost_primary_ranking.py::test_primary_ranking_report_contains_ml_and_baseline_fields",
    "tests/test_xgboost_primary_ranking.py::test_candidates_are_sorted_by_xgboost_score_descending",
    "tests/test_xgboost_primary_ranking.py::test_script_generates_reports_without_modifying_inputs",
    "tests/test_feature_importance_exports.py::test_random_forest_feature_importance_is_generated_if_model_exists",
    "tests/test_demo_end_to_end.py::test_demo_end_to_end_generates_manifest_and_summaries_without_mutating_inputs",
    "tests/test_decision_cards_ml_comparison.py::test_decision_cards_ml_comparison_is_generated_without_modifying_inputs",
    "tests/test_ml_experiment_reports.py::test_interpretation_generator_runs",
})

# Tests that need ranking dataset JSONL files (unlabeled, pseudo-labeled, aligned)
_RANKING_DATASETS_NODEIDS = frozenset({
    "tests/test_ranking_dataset.py::test_global_unlabeled_dataset_exists",
    "tests/test_ranking_dataset.py::test_unlabeled_dataset_contract",
    "tests/test_ranking_dataset.py::test_dataset_summary_is_consistent",
    "tests/test_ranking_evaluation.py::test_dataset_is_loaded_correctly",
    "tests/test_ranking_evaluation.py::test_extracts_12_features_and_uses_label_binary_target",
    "tests/test_ranking_evaluation.py::test_identifiers_are_not_used_as_features",
    "tests/test_ranking_evaluation.py::test_group_rows_by_job_id_and_ranking_metrics_are_valid",
    "tests/test_pseudo_labels.py::test_pseudo_labels_contract",
    "tests/test_pseudo_labels.py::test_pseudo_label_summary_distribution_non_empty",
    "tests/test_pseudo_label_rule_simulation.py::test_pseudo_label_rule_simulation_report_exists",
    "tests/test_pseudo_label_rule_simulation.py::test_simulation_does_not_modify_official_dataset",
    "tests/test_aligned_dataset_generation.py::test_aligned_dataset_artifacts_exist_and_are_filtered",
    "tests/test_aligned_dataset_generation.py::test_aligned_pseudo_labels_exist_without_training_fields",
    "tests/test_aligned_dataset_generation.py::test_build_ranking_dataset_supports_include_job_ids_without_modifying_old_dataset",
    "tests/test_demo_summary.py::test_demo_summary_is_generated_without_modifying_dataset",
    "tests/test_demo_executive_summary.py::test_demo_executive_summary_generation",
    "tests/test_candidate_corpus_analysis.py::test_analysis_does_not_modify_existing_datasets",
    "tests/test_decision_cards_with_transferability.py::test_decision_cards_with_transferability_generated_without_modifying_inputs",
})

# Tests that need any v3 matching report on disk
_MATCHING_V3_REPORT_NODEIDS = frozenset({
    "tests/test_matching_v3_report_contract.py::test_matching_report_exists_and_has_recommendations",
    "tests/test_matching_v3_report_contract.py::test_matching_recommendations_have_required_fields",
    "tests/test_matching_v3_report_contract.py::test_scores_are_bounded",
    "tests/test_matching_v3_report_contract.py::test_seniority_fields_are_valid",
    "tests/test_matching_v3_report_contract.py::test_no_fake_supervised_fields_in_matching_report",
    "tests/test_matching_v3_report_contract.py::test_feature_jsonl_consistent_with_matching_seniority",
    "tests/test_ranking_features.py::test_generated_matching_report_contains_seniority_fields",
    "tests/test_transferability_score.py::test_script_generates_report_without_modifying_inputs",
})

# Tests that need docs/reports/matching/v3/decision_cards_v3_normalized.json
_DECISION_CARDS_V3_NODEIDS = frozenset({
    "tests/test_candidate_identity.py::test_resolve_candidate_display_name_from_grounded_profile",
    "tests/test_candidate_identity.py::test_resolve_candidate_display_name_from_decision_card",
    "tests/test_candidate_identity.py::test_resolve_candidate_display_name_for_aziz",
    "tests/test_candidate_identity.py::test_enrich_candidate_with_display_name_does_not_change_scores",
    "tests/test_candidate_identity.py::test_enrich_candidates_with_display_names_preserves_order",
})

# Tests that need CV fixture files (Image_73.pdf, Hichem_resume.pdf, etc.)
_CV_FIXTURES_NODEIDS = frozenset({
    "tests/test_candidate_cv_resolver.py::test_resolve_candidate_cv_returns_image_73_for_ml_job",
    "tests/test_candidate_cv_resolver.py::test_resolve_candidate_cv_returns_hichem_image_for_ml_job",
    "tests/test_candidate_cv_resolver.py::test_resolve_candidate_cv_returns_jessica_pdf_for_ml_job",
    "tests/test_candidate_cv_resolver.py::test_resolve_candidate_cv_prefers_ml_pdf_and_keeps_docx_alternative",
    "tests/test_api_candidate_cv.py::test_candidate_cv_endpoint_returns_existing_cv",
})

# Tests that need data/ranking/annotations/annotation_sample.csv
_ANNOTATION_SAMPLE_NODEIDS = frozenset({
    "tests/test_annotation_sample.py::test_annotation_sample_exists_and_has_no_auto_labels",
    "tests/test_annotation_sample.py::test_annotation_sample_has_no_duplicate_job_candidate_pairs",
    "tests/test_annotation_sample.py::test_annotation_sample_covers_top_middle_low_when_available",
})

# Tests that need the legacy v2 grounded profiles directory
_GROUNDED_PROFILES_NODEIDS = frozenset({
    "tests/test_transferability_score.py::test_compute_transferability_score_shape",
})

# Tests that need docs/reports/ml/ml_experiment_interpretation.json
_ML_EXPERIMENT_REPORTS_NODEIDS = frozenset({
    "tests/test_ml_experiment_reports.py::test_ml_experiment_interpretation_report_exists_and_documents_limits",
})

# Tests that need docs/reports/copilot/copilot_evaluation.json
_COPILOT_REPORTS_NODEIDS = frozenset({
    "tests/test_copilot_evaluation.py::test_copilot_evaluation_reports_are_generated",
    "tests/test_copilot_evaluation.py::test_copilot_evaluation_json_contains_required_metrics",
    "tests/test_copilot_evaluation.py::test_copilot_evaluation_markdown_is_readable",
})


# ---------------------------------------------------------------------------
# Auto-skip hook
# ---------------------------------------------------------------------------

def pytest_collection_modifyitems(config: pytest.Config, items: list[pytest.Item]) -> None:
    artifact_available = _artifact_mode_available()
    demo_available = _demo_reports_available()
    neo4j_available = _neo4j_report_available()
    ranking_models_available = _ranking_models_available()
    ranking_datasets_available = _ranking_datasets_available()
    matching_v3_available = _matching_v3_report_available()
    decision_cards_v3_available = _decision_cards_v3_available()
    cv_fixtures_available = _cv_fixtures_available()
    annotation_sample_available = _annotation_sample_available()
    grounded_profiles_available = _grounded_profiles_available()
    ml_experiment_reports_available = _ml_experiment_reports_available()
    copilot_reports_available = _copilot_reports_available()

    artifact_skip = pytest.mark.skip(reason=_ARTIFACT_SKIP_REASON)
    report_skip = pytest.mark.skip(reason=_REPORT_SKIP_REASON)
    ml_pipeline_skip = pytest.mark.skip(reason=_ML_PIPELINE_SKIP_REASON)
    cv_fixtures_skip = pytest.mark.skip(reason=_CV_FIXTURES_SKIP_REASON)
    matching_report_skip = pytest.mark.skip(reason=_MATCHING_REPORT_SKIP_REASON)
    decision_cards_skip = pytest.mark.skip(reason=_DECISION_CARDS_SKIP_REASON)
    annotation_skip = pytest.mark.skip(reason=_ANNOTATION_SKIP_REASON)
    grounded_profiles_skip = pytest.mark.skip(reason=_GROUNDED_PROFILES_SKIP_REASON)
    ml_reports_skip = pytest.mark.skip(reason=_ML_REPORTS_SKIP_REASON)
    copilot_reports_skip = pytest.mark.skip(reason=_COPILOT_REPORTS_SKIP_REASON)

    for item in items:
        nid = item.nodeid.replace("\\", "/")

        if not artifact_available and nid in _ARTIFACT_DEPENDENT_NODEIDS:
            item.add_marker(artifact_skip)
        elif not demo_available and nid in _DEMO_REPORT_NODEIDS:
            item.add_marker(report_skip)
        elif not neo4j_available and nid in _NEO4J_REPORT_NODEIDS:
            item.add_marker(report_skip)
        elif not ranking_models_available and nid in _RANKING_MODELS_NODEIDS:
            item.add_marker(ml_pipeline_skip)
        elif not ranking_datasets_available and nid in _RANKING_DATASETS_NODEIDS:
            item.add_marker(ml_pipeline_skip)
        elif not matching_v3_available and nid in _MATCHING_V3_REPORT_NODEIDS:
            item.add_marker(matching_report_skip)
        elif not decision_cards_v3_available and nid in _DECISION_CARDS_V3_NODEIDS:
            item.add_marker(decision_cards_skip)
        elif not cv_fixtures_available and nid in _CV_FIXTURES_NODEIDS:
            item.add_marker(cv_fixtures_skip)
        elif not annotation_sample_available and nid in _ANNOTATION_SAMPLE_NODEIDS:
            item.add_marker(annotation_skip)
        elif not grounded_profiles_available and nid in _GROUNDED_PROFILES_NODEIDS:
            item.add_marker(grounded_profiles_skip)
        elif not ml_experiment_reports_available and nid in _ML_EXPERIMENT_REPORTS_NODEIDS:
            item.add_marker(ml_reports_skip)
        elif not copilot_reports_available and nid in _COPILOT_REPORTS_NODEIDS:
            item.add_marker(copilot_reports_skip)
